export type CategoryKey =
  | "ATM"
  | "BILL_PAYMENT"
  | "CASH"
  | "CASHBACK"
  | "CHEQUE"
  | "CORRECTION"
  | "CREDIT"
  | "DIRECT_DEBIT"
  | "DIVIDEND"
  | "FEE_CHARGE"
  | "INTEREST"
  | "OTHER"
  | "PURCHASE"
  | "STANDING_ORDER"
  | "TRANSFER"
  | "DEBIT"
  | "UNKNOWN";
